### ISSUE TITLE
Repeated error for starting without ARL, fails to work

### ISSUE THREAD

**Issue by IronPiston** [Bockiii/deemix-docker#11]
After restarting the docker image, deemix refused to load. After killing and recreating the image multiple times, it still refuses to work as it did yesterday. Checking the [logs](https://paste.ee/p/bZsic), there is a repeated error that occurs until I eventually stop deemix.

**Comment by Bockiii** [comment]
You don't have the latest image. Do a docker pull (or docker-compose pull) and try again. It will work.

**Comment by IronPiston** [comment]
Running a docker pull still doesn't rectify the issue, I'm getting the same errors as in the initial post

**Comment by Bockiii** [comment]
Is the log really exactly the same?

Because in the screenshot, you are only pulling from one repo, which is the "old" way before they restructured. In the new way, you will get an entry saying that its cloning 2 repos.

see https://paste.ee/p/xvxC6 (lines 31+)

If you dont see that in your log, you dont have the latest container and it will fail.

**Comment by IronPiston** [comment]
I force removed the image and pulled it again. This seems to have fixed the issue.
